version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mediazilla_interview
      - POSTGRES_PASSWORD=interview
      - POSTGRES_DB=mediazilla_interview_development

  test_db:
    image: postgres
    volumes:
      - ./tmp/test_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test_mediazilla_interview
      - POSTGRES_PASSWORD=test_interview
      - POSTGRES_DB=test_mediazilla_interview_development

  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - test_db
    environment:
      - POSTGRES_USER=mediazilla_interview
      - POSTGRES_PASSWORD=interview
      - POSTGRES_DB=mediazilla_interview_development
      - TEST_POSTGRES_USER=test_mediazilla_interview
      - TEST_POSTGRES_PASSWORD=test_interview
      - TEST_POSTGRES_DB=test_mediazilla_interview_development
